CESNET/perun-proxy-api

- src/test/resources/application.yml
- src/test/resources/basicauth.yml
- because of missing properties, build was not passing, there were test
failures
> Fixed build failures

- pom.xml
- src/main/java/cz/muni/ics/perunproxyapi/PerunProxyApiApplication.java
- src/main/java/cz/muni/ics/perunproxyapi/application/endpointproviders/DeveloperInfo.java
- src/main/java/cz/muni/ics/perunproxyapi/application/endpointproviders/GitInfoProperties.java
- src/main/java/cz/muni/ics/perunproxyapi/application/endpointproviders/InfoEndpointProvider.java
- src/main/resources/application.yml
- configured actuator /health and /info endpoints to display additional
information
- info
- displays properties from pom.xml (version, package, developers, ...)
- Also displays info from Git. Package application to generate the
git.properties file.
- health
- displays status of application (UP)
> Actuator configuration - info and health

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- @NonNull annotation is not applicable when mapping attributes
- added building of the prefix when looking for attributes of an entity
> Fixed searching for AttrValues and mapper

- config_templates/attributes.yml.tpl
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/AttributeObjectMapping.java
- added support for separator in case of attrType = MAP_KEY_VALUE for AttributeMapping
> Added separator field in attrMapping

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeValue.java
- removed NULL as a special object, rather return object with type but value as NullNode
> Refactored PerunAttributeValue

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
RpcMapper could produce NullPointerException when NullNode was given as an argument of its methods.
> RpcMapper fix

- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/AttributeObjectMapping.java
- the directive in the annotation for generating equals and hashCode caused different object to produce same hashCode (and were considered as equal)
- removing the directive fixes the issue
> Fixed AttributeObjectMapping hashCode and equals

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
Method getUserByLogin could produce nullPointerException if user was not found.
> ProxyUserFacadeImpl - bugfix

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/DTOModels/UserDTO.java
UserDTO's perunAttributes should always be at least empty map, it shouldn't be a null.
> Added @NonNull annotation to UserDTO's perunAttributes

- src/main/java/cz/muni/ics/perunproxyapi/persistence/AttributeMappingService.java
- src/test/resources/attributes.yml
- the bug caused the ability to configure two attributes with the same
identifier
- fixed wrong configuration for tests
> Fixed bug in AOMservice

- pom.xml
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/PerunConnectorRpc.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/properties/RpcConnectorProperties.java
- src/main/resources/application.yml
- src/test/resources/application.yml
- use @ConfigurationProperties for RPC connector
> Refactored RPC config

- PULL_REQUEST_TEMPLATE.md
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserMiddleware.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserMiddlewareImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
> findByUserId API method

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/FacadeUtils.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- new Utility class that contains common methods used by facade layer
> Facade utilities

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/properties/RpcConnectorProperties.java
- Added some null checks
- Removed some unused imports
> Code refactor

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
Renaming middleware to service
> Use 'service' instead of 'middleware'

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
Fixed some issues when fetching attributes
> Fixed some issues when fetching attributes

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
- src/main/resources/application.yml
- src/test/resources/application.yml
- methods now do not have to use the default_idp property
- instead, use getting the user by the login attribute directly
> Refactored fetching entitlements

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/FacadeUtils.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- src/main/resources/application.yml
- src/test/resources/application.yml
> findByIdentifiers API method

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- fixed some bugs and possible null pointers in the LDAP adapter
- improved code readability a bit
> Fixes in LDAP adapter

- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/RelyingPartyProtectedController.java
- added some missing annotations to the REST layer
- added missing documentation
> Rest layer documentation + improvements

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- some methods were returning USER instead, changed to UserDTO
> Facade and REST should return UserDTO

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/AdapterUtils.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/User.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- Login is now part of the User bean. Fetch it as well with other user
things.
> Fetch login for users

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/Facility.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/User.java
Fetch RpIdentifier for facility
> Fetch RpIdentifier for facility

- src/test/java/cz/muni/ics/perunproxyapi/PerunProxyApiApplicationTest.java
- src/test/resources/application.yml
- src/test/resources/attributes.yml
- attributes.yml did not contain required mappings for constructing
adapters
> Fixed test failures

- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/AttributeObjectMapping.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/ExtSource.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/Facility.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/Group.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttribute.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/Resource.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/User.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/UserExtSource.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/Vo.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/DTOModels/UserDTO.java
- this caused annotations not to be applied
- missing annotations were causing some checks to be missing
> Fixed missing annotations on non generated methods in models

- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/User.java
> Removed redundant call of setPerunId in User model

- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttribute.java
- this field is already present in the PerunAttributeAware abstract
class
> Removed duplicate "type" field form PerunAttribute

- openapi.yml
> Added openapi.yml file to project

- src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/InvalidRequestParameterException.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/ExceptionResolver.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/RelyingPartyProtectedController.java
- src/main/resources/application.yml
- src/test/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedControllerTest.java
- return correct response code when inputs do not meet criteria
- disable stacktrace printing for response bodies
> Controller level input validation

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/FullAdapter.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/enums/Entity.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeValueAwareModel.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntry.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- src/test/resources/configs/proxyuser-facade.yml
> Update user identity attributes

- src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/PerunConnectorRpc.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/properties/RpcConnectorProperties.java
- src/main/resources/application.yml
- src/test/resources/application.yml
- can specify serializer that will be used for RPC
- is dependent on what serializers RPC does support
> Option for serializer in RPC

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- it should use exact match in one of the values instead of like
matching
> Fix additional identifiers

- src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/PerunConnectorLdap.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/PerunConnectorRpc.java
- added @NonNull annotations to parameters
- refactored logging of parameters used for calls
> Refactored connectors, improved their logs.

- src/main/java/cz/muni/ics/perunproxyapi/persistence/AttributeMappingService.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/ConfigurationException.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/AttributeObjectMapping.java
- log when an error has occurred in Adapters for easier failure tracing
- log in AOMService as well
> Better logging for AttributeObjectMappings

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImplTestUserRelated.java
- src/test/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedControllerTest.java
- method now accepts passing fields from the request
- if no fields are specified, default from config is used
> Find user by perun user ID accepts fields

- pom.xml
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/DataAdapter.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ControllerUtils.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/RelyingPartyProtectedController.java
- src/test/java/cz/muni/ics/perunproxyapi/application/facade/ProxyUserFacadeTest.java
- src/test/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserServiceTest.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImplTestUserRelated.java
- src/test/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedControllerTest.java
- added POST mappings for finding users
- introduced base64 encoding of IdPIdentifiers and RPIdentifiers
- [] Bug fix (non-breaking change which fixes an issue)
> Update methods for Proxyuser REST

- openapi.yml
> Updated OpenAPI specification

- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntry.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/AttributeObjectMappingTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/ExtSourceTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/FacilityTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/GroupTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/MemberTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeValueTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/ResourceTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/UpdateAttributeMappingEntryTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/UserExtSourceTests.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/UserTests.java
- Added tests for creating models
- Tests focus on passing illegal arguments to the constructors and setters.
> Tests for models

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/test/java/cz/muni/ics/perunproxyapi/TestUtils.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImplTestUserRelated.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImplUserRelatedTest.java
- src/test/resources/configs/proxyuser-facade.yml
Tests for RPC user related adapter methods.
> Tests for RPC user related adapter methods

- src/main/java/cz/muni/ics/perunproxyapi/application/facade/FacadeUtils.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
- default fields are used only when no fields are passed
- if the fields are passed as an empty list, it will be used instead of
using default ones
- improved logging
> Default fields and logs.

- src/main/java/cz/muni/ics/perunproxyapi/ga4gh/Ga4ghBeans.java
- src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/config/ElixirGa4ghConfig.java
> Fixes in GA4GH loading

- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/exceptions/MissingFieldException.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImplUserRelatedTest.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapperTest.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapperTests.java
> Tests for mappers

- pom.xml
- prepares the application to be used with JDK 15
- updated Jacoco maven plugin to its latest version to support newer class files versions
- updated Spring Boot Starter Parent to its latest version just to be sure 
- just the pom.xml was updated, no code
> support JDK 15

- CHANGELOG.md
- openapi.yml
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/FacadeUtils.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/ProxyuserFacade.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/ProxyuserFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ProxyUserService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/ServiceUtils.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/FullAdapter.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/connectors/PerunConnectorRpc.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/Candidate.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/ExtSource.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/UserExtSource.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ControllerUtils.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/ProxyUserProtectedController.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/RelyingPartyProtectedController.java
- src/test/resources/configs/proxyuser-facade.yml
> createMemberInVO API method

- CHANGELOG.md
- src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/ActiveClaimRepository.java
- src/main/java/cz/muni/ics/perunproxyapi/ga4gh/model/ClaimRepository.java
- src/main/java/cz/muni/ics/perunproxyapi/ga4gh/service/impl/ElixirGa4ghService.java
- some repositories in the GA4GH configuration need multiple request headers to be supported
- instead of specifying just one request header via _auth_header_ and _auth_value_ options, specify list via key _headers_
- each element  has to have two properties: _header_ (name of the header) and _value_ (value for the header)
> Extended GA4GH headers configuration

- openapi.yml
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/RelyingPartyFacade.java
- src/main/java/cz/muni/ics/perunproxyapi/application/facade/impl/RelyingPartyFacadeImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/RelyingPartyService.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/ProxyUserServiceImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/RelyingPartyServiceImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/ldap/LdapAdapterImpl.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapper.java
- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/Group.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/controllers/RelyingPartyProtectedController.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/adapters/impl/rpc/RpcMapperTest.java
- src/test/java/cz/muni/ics/perunproxyapi/persistence/models/GroupTests.java
> Added extended entitlements

- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/RelyingPartyServiceImpl.java
> Fixed: Two same entitlements were added for each group

- src/main/java/cz/muni/ics/perunproxyapi/persistence/models/PerunAttributeValueAwareModel.java
- used to return a list containing null if converted from a string
> Fixed valueAsList() method for PerunValue aware classes

- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/config/WebConfig.java
- src/main/java/cz/muni/ics/perunproxyapi/presentation/rest/config/WebSecurityConfiguration.java
- src/main/resources/static/js/stats.js
> Fix webjars auth

- src/main/java/cz/muni/ics/perunproxyapi/application/service/impl/RelyingPartyServiceImpl.java
> update query separator
